
# Use an official Node.js runtime as a parent image
FROM node:16-alpine

LABEL version="1.0"
LABEL description="React Frontend for the Library API"

# Set the working directory to /app
WORKDIR /usr/src/app

# Copy package.json contents into the container at ./
COPY --chown=node:node package.json ./
COPY --chown=node:node package-lock.json ./

# Install any needed dependencies specified in package.json
RUN npm install

# Copy everything inside the client into the folder inside the app
COPY --chown=node:node . . 

CMD ["npm","start"]