#  Dockerfile for Node Express Backend api (development)
FROM node:14.15.3-alpine3.12

# Set the working directory to /app
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /app
COPY --chown=node:node package.json ./
COPY --chown=node:node package-lock.json ./

# Install any needed dependencies specified in package.json
RUN npm install 

COPY --chown=node:node . .

CMD ["npm","start"]